config/routes.rb
SocialpriceComVe::Application.routes.draw do

  root :to => 'home#index'

  resources :training

end

app/models/post.rb
class Post
  include Mongoid::Document
  field :actual, type: String
  field :text, type: String
  field :nuevo, type: String

end

app/models/product.rb
class Product
  include Mongoid::Document

  field :name, :type => String
  field :barcode, :type => String
  field :existence, :type => Boolean
  field :price, :type => Float
  field :marca, :type => String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  def index
  end
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController
  before_filter :totales

  def totales
    @procesados = Post.where(:nuevo.in => ["p","n","nt"]).count
    @totales = Post.count
    @porcentaje = ((@procesados.to_f * 100.to_f) / @totales.to_f).round(2)
  end
  def index
    @posts = Post.order_by.page params[:page]
    @page = params[:page]
  end

  def update
    @post = Post.find params[:id]
    @post.update_attributes(params[:post])
    @post.save
    @posts = Post.order_by.page params[:page]
    @page = params[:page]
    #redirect_to '/training?page=' + params[:page].to_s
  end

  def destroy
    @post = Post.find params[:id]
    @post.delete unless @post.nil?
    #redirect_to '/training?page=' + params[:page].to_s
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/home/index.html.erb
<h1>SocialPrice</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SocialpriceComVe" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag %>
  </head>
  <body>

    <%= yield %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SocialPrice.com.ve" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag %>
  </head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><%= content_for?(:title) ? yield(:title) : "SocialPrice.com.ve" %></a>

        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit center">
        <h1>SocialPrice</h1>
        <p>La compra más inteligente y eficiente.</p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>A los Consumidores</h2>
          <p>Guía de compras eficiente y siempre actualizada que fomenta el ahorro. </p>
        </div>
        <div class="span4">
          <h2>A los Minoristas</h2>
          <p>Presencia en Internet a Bajo Costo. </p>
       </div>
        <div class="span4">
          <h2>A las Marcas</h2>
          <p>Social Media y exposición directa de las marcas.</p>
        </div>
      </div>

      <hr>

      <footer>
        <p>© SocialPrice 2012</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/training/destroy.js.erb
$('#<%= @post.id %>').remove();
$('#info').replaceWith('<span id="info">Porcentaje Procesado: <%= @porcentaje %>% (<%= @procesados %> de <%= @totales %>)</span>');

app/views/training/index.html.erb
<div><span id="info">Porcentaje Procesado: <%= @porcentaje %>% (<%= @procesados %> de <%= @totales %>) </span> </div>
<!--       <div id="loading" style="hide"><img src="http://www.tram.cat/images/ajax-loader.gif"> </div> -->
      <table class="span8 table table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th style="text-align:left">Texto</th>
            <th>Actual</th>
            <th>Nuevo</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr style="<%= "background-color:#93DAD7" unless post.nuevo.nil? || post.nuevo.empty? %>" id="<%= post.id %>" >
              <%= form_for(post, {:remote => true, :url => training_path(post), :method => 'put'}) do |p| %>
              <td class="span6">
                <p><%= p.label post.text.to_s %></p>
              </td>
              <td><%= p.label post.actual.to_s %></td>
              <td class="span3">
                Positivo <%= p.radio_button :nuevo, 'p' %>
                <br>
                Negativo <%= p.radio_button :nuevo, 'n' %>
                <br>
                Neutro <%= p.radio_button :nuevo, 'nt' %>
              </td>
              <td>
                <%= hidden_field_tag 'page', @page %>
                <%= p.submit 'update', :class => "btn btn-mini btn-primary" %>
                <%= link_to 'delete', training_path(post) + '?page=' + @page.to_s, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "btn btn-mini btn-danger" %> 
              </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
        <div><%= paginate @posts %></div>
      </table>

app/views/training/update.js.erb
$('#<%= @post.id %>').css("background-color","#93DAD7");
$('#info').replaceWith('<span id="info">Porcentaje Procesado: <%= @porcentaje %>% (<%= @procesados %> de <%= @totales %>)</span>');